name: Csv Data Processing
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
jobs:
  prepare_environment:
    runs-on: ubuntu-latest
    steps:
    - name: loading packages
      run: python app.py
