name: Csv Data Processing
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
jobs:
  prepare_environment:
    runs-on: windows-latest
    steps:
    - name: Hello
      run: python -c "print('Hello world')"
    - name: loading packages
      run: python C:/Users/USER/Documents/Master2 DIT/Outil versioning/versioning/app.py
